package com.akarin.webapp.util;

import java.util.Map;

public class PageRender {

    public static String getGenericHeader() {
        return "<div id=\"sr-header-area\"><div id=\"srLeftContainer\" class=\"sr-bar\"><div id=\"srDropdown\"><div id=\"srDropdownContainer\"><a href=\"javascript:void 0\">My Subreddits</a></div></div><div id=\"RESStaticShortcuts\"><span class=\"separator\">-</span><a id=\"RESDashboardLink\" class=\"subbarlink undefined\" href=\"/r/Dashboard/\">Dashboard</a><span class=\"separator\">-</span><a class=\"subbarlink undefined\" href=\"/\">home</a><span class=\"separator\">-</span><a class=\"subbarlink undefined\" href=\"/r/popular/\">popular</a><span class=\"separator\">-</span><a class=\"subbarlink RESShortcutsCurrentSub\" href=\"/r/all/\">All</a><span class=\"separator\">-</span><a class=\"subbarlink\" href=\"/r/random/\">Random</a><span class=\"separator\">-</span><a class=\"subbarlink\" href=\"/users/\">Users</a><span class=\"separator\">-</span><a class=\"subbarlink undefined\" href=\"/r/friends/\">Friends</a><span class=\"separator\">-</span><a class=\"subbarlink\" href=\"/user/me/saved\">Saved</a><span class=\"separator\">-</span><a class=\"subbarlink\" href=\"#res:settings/subredditManager\" title=\"RES Settings > Subreddit Manager\">edit</a></div><span class=\"srSep\">|</span></div><div id=\"RESShortcutsViewport\"><div id=\"RESShortcuts\" class=\"sr-bar\"><a draggable=\"true\" orderindex=\"0\" data-subreddit=\"anime\" class=\"subbarlink\" href=\"/r/anime\">anime</a><span class=\"separator\">-</span><a draggable=\"true\" orderindex=\"1\" data-subreddit=\"DotA2\" class=\"subbarlink\" href=\"/r/DotA2\">dota2</a><span class=\"separator\">-</span><a draggable=\"true\" orderindex=\"2\" data-subreddit=\"wow\" class=\"subbarlink\" href=\"/r/wow\">wow</a></div></div><div id=\"RESShortcutsEditContainer\"><div id=\"RESShortcutsSort\" title=\"sort subreddit shortcuts\">↑↓</div><div id=\"RESShortcutsRight\">&gt;</div><div id=\"RESShortcutsAdd\" class=\"res-icon\" title=\"add shortcut\">\uF139</div><div id=\"RESShortcutsLeft\">&lt;</div></div></div>";
    }
}
